language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install tox
script:
- pytest
- tox
deploy:
  provider: pypi
  user: finish06
  password:
    secure: oBm5iBwFKsETqwdL2ZjPtLKiHfwUDyV4oB6sSFxtigsnf4RKYXyCE+gTkaT6LMUH1O0X/tTsPkoCURvuuUuKJx/9JzHkXlNXgr/gIyGvNmD+Tc6NAO7G1ZWA1Thso/g3UzLPB0PMxMVFp/pcpe4q0B4C5wxkjg+WbGW0IMYsriLoZaVuFFibwaFzRAr9vXpXjESYvkxEs1yRx3TRM9JKzCvUIu05kGXabBAs8P54Xi2QfP1Y82CqkF2xElUTU06/BM6r3nGDKj+ZIOMfvlnMMPHcjaxOxLF1HCM+1mEUooUMBE93K5Md78fkJgDP/orvvphyn03gBCppeEqLEkblQ1byFz1NrHDnjdGCa4DVkBBohWZf7qgfPI59XR9UpNPfbM82wWwmfAvrGmJeLmmzv3rml5CPWuYb+MKKj20L2dYYrmclxP2GtIF7XAfAJZfVlpDPkFFED1LyWp2zQj0ZkwOW9L/6rnVC8LS56GBDEw2MwN4aaBIpLOLTkqHWtfxBvHRlhQvI6Z3F7rRg6VEEur5mx6B9rAE1nj2jpSzUfmem9B7imMC4mXSKypqKpj5NqXBUOqJlibS2Ab+BnpDtZyn5odsZsH0jfOyQk6etAtGmJkoepRU/qlilt8y4LinoXQb1DRn78RwlIoR9ZYbgwHJDylyeK9z36kiF7b9U3EY=
  on:
    tags: true
    branch: master